### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by stephaneyfx** [stephaneyfx/brightness#2]
Work in progress in the [windows branch](https://github.com/stephaneyfx/brightness/tree/windows). It fails on my laptop with the message "An error occurred while transmitting data to the device on the I2C bus". This error also occurs when calling `GetMonitorCapabilities`.

**Comment by jacob-pro** [comment]
I literally started writing half of this last night lol. 
https://github.com/jacob-pro/brightness/commit/f4a438d4ce54250923a51bc3b6e38fd7e9ec7aaf
Like I said I have done this before, so I should be able to get it working.
Just trying to find a way to get a unique name/id for each physical display, szPhysicalMonitorDescription isn't that useful

**Comment by stephaneyfx** [comment]
The code in the `windows` branch might already work; it might just be an issue with my laptop (based on a cursory search, not all laptops support what `GetMonitorBrightness`, etc., use under the hood).

Regarding a unique ID, there's [`GetMonitorInfo`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa) but that takes a `HMONITOR`, which can be mapped to multiple physical monitors AFAIK, so it's not quite what we need.

**Comment by jacob-pro** [comment]
yeah that is because the Get/Set MonitorBrightness APIs use DDC/CI which is for external but not laptop screens. I think there is a seperate API for laptop screens although I haven't read up the details yet... I will have a PR for it soon

**Comment by stephaneyfx** [comment]
Implemented by @jacob-pro in #3. Thank you very much!
