### ISSUE TITLE
EnumerationMismatch on Windows

### ISSUE THREAD

**Issue by jacob-pro** [stephaneyfx/brightness#4]
So it would appear that my assumption that EnumDisplayDevicesW and EnumDisplayMonitors return the same set of results may not actually be the case :(

https://github.com/stephaneyfx/brightness/blob/494110022b4e86ad859efec09dc507934b3f15bb/src/windows.rs#L212-L217

@mruac is getting experiencing the issue on their setup here:
https://github.com/jacob-pro/solar-screen-brightness/issues/10

Edit: This error is occuring when an external display is plugged in but not enabled in Windows settings.

**Comment by jacob-pro** [comment]
# Background

## Step 1:

We call `EnumDisplayMonitors()` and this returns a list of `HMONITOR` handles.

For each of these handles we then call `GetMonitorInfoW()` which gives us the string `szDevice`
These look like: "\\.\DISPLAY1" and "\\.\DISPLAY2" etc.

## Step 2:

We call `GetPhysicalMonitorsFromHMONITOR()` for each of the `HMONITOR` handles and get back a list of `PHYSICAL_MONITOR` structs.

A `PHYSICAL_MONITOR` contains two interesting items: a `HANDLE` and string `szPhysicalMonitorDescription`.
An example of `szPhysicalMonitorDescription` is "SC650_S24C650BW / S24C650MW (Digital)", however this of course **is not unique**, if you have two identical monitors connected then they will show the same description.

The physical monitor `HANDLE` is used for getting/setting brightness on external DDC/CI displays.
**I am not currently aware of a way of any functions we can use to get more info from this physical monitor handle**

## Step 3:

We call `EnumDisplayDevicesW()` for each of the `HMONITOR` `szDevice` names and get back a list of `DISPLAY_DEVICEW` structs.
The `DISPLAY_DEVICEW` contains some interesting fields, for example:

```
StateFlags: 3
DeviceName: \\.\DISPLAY1\Monitor0
DeviceString: SC650_S24C650BW / S24C650MW (Digital)
DeviceID: \\?\DISPLAY#SAM09CF#5&397a0ebd&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
DeviceKey: \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
```

Note 1: The value of `DeviceID` changes depending on if the flag `EDD_GET_DEVICE_INTERFACE_NAME` was set.
Without it set we would get "MONITOR\SAM09CF\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002" instead.

Note 2: The `DeviceString` is equal to the `szPhysicalMonitorDescription` but as mentioned above unfortunately not unique.

We then use the `DeviceID` to open a `HANDLE` using the `CreateFileW()` API, this `HANDLE` can be used to set the brightness of a laptop screen using the `DeviceIoControl()` API. However the `CreateFileW()` and `GetPhysicalMonitorsFromHMONITOR()` `HANDLE`s **are not compatible.**

# What is a HMONITOR?

When 2 monitors are connected there are 4 options:

- Extend these displays
- Duplicate these displays
- Show only on 1
- Show only on 2

In extend there will be two `HMONITOR`s "\\.\DISPLAY1" and "\\.\DISPLAY2" each containing a "Monitor0"

In duplicate there will be one `HMONITOR` "\\.\DISPLAY1" containing "Monitor0" and "Monitor1"

In show only on X there will only be one `HMONITOR`, but interestingly:
- `GetPhysicalMonitorsFromHMONITOR()` will return 1 physical monitor (the one switched on)
- `EnumDisplayDevicesW()` will return 2 display devices (including the one that is inactive)

# Associating a `PHYSICAL_MONITOR` and `DISPLAY_DEVICEW`

This is the challenging part which I have found no good answer to - there does not seem to be any unique identifier we can get from the `PHYSICAL_MONITOR`?

Some discussions on this:
- [StackOverflow - How to associate PHYSICAL_MONITOR with monitor DeviceID](https://stackoverflow.com/questions/63095216/how-to-associate-physical-monitor-with-monitor-deviceid)
- [MSDN - How to get hardware id from a monitor handle](https://social.msdn.microsoft.com/Forums/windows/en-US/4353d92b-9358-473e-919c-4c8827c7a1d1/how-to-get-hardware-id-from-a-monitor-handle?forum=vcgeneral)
- [MSDN - How to locate the EDID data folder/key in the registry, which belongs to a specific PHYSICAL_MONITOR object](https://social.msdn.microsoft.com/Forums/healthvault/en-US/efc46c70-7479-4d59-822b-600cb4852c4b/how-to-locate-the-edid-data-folderkey-in-the-registry-which-belongs-to-a-specific-physicalmonitor?forum=wdk)

## What we are doing now:

Assuming that:
- `GetPhysicalMonitorsFromHMONITOR()` and `EnumDisplayDevicesW()` return devices in the same order as each other
- Hoping that there are no disconnections/reconnections in between the two function calls

With the sanity check that the two arrays are the same length (`EnumerationMismatch` error).

## What other people are doing

I wonder how [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html) (closed source) has solved this problem?

Interestingly when [running DUMPBIN on the exe](https://stackoverflow.com/a/475323/7547647) I can see it doesn't actually link to `Dxva2.dll` to use any of the [Monitor Configuration](https://docs.microsoft.com/en-us/windows/win32/api/_monitor/) APIs.

It does however still call `EnumDisplayDevicesW()` so maybe they have found an alternative method of using DDC control that uses the one of the IDs returned in a `DISPLAY_DEVICEW`?

There is also [ClickMonitorDDC](https://web.archive.org/web/20200803212815/https://clickmonitorddc.bplaced.net/) which does use the `Dxva2.dll` functions, but it is also closed source.

Maybe we could do some reverse engineering of these two binaries?

## WMI API

We are currently using `DeviceIoControl()` API for laptop screens which has actually been deprecated in favour of the [WmiMonitorBrightness class](https://docs.microsoft.com/en-us/windows/win32/wmicoreprov/wmimonitorbrightness).

However migrating to this wouldn't seem to solve any of the difficulty here because the `WmiMonitorBrightness` only supports laptop screens - we still need to use the Monitor Configuration APIs for DDC/CI.

Example:

```powershell
# Lists all monitors (internal and external)
gwmi WmiMonitorID -Namespace root\wmi

# Lists laptop screens (returns "Not supported" on desktops)
gwmi WmiMonitorBrightness -Namespace root\wmi
```

# Workaround

I have observed that when in "Show only on 1" display is enabled, the disabled display does not have the [DISPLAY_DEVICE_ACTIVE](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-display_devicew) set in `StateFlags`.

We can therefore work around this by filtering out the inactive displays. Unhelpfully the docs are actually incorrect since they claim "EnumDisplayDevices will only enumerate monitors that can be presented as being on." which is clearly false.

We may also need to filter out displays with the `DISPLAY_DEVICE_MIRRORING_DRIVER` flag set, but I have not yet been able to replicate / test this so I am hesitant to add to this PR for now.

**Comment by stephaneyfx** [comment]
Thank you very much for the in-depth write-up @jacob-pro !
Do you think this issue should be closed? My understanding is that the implemented fix is not perfect but resolves the original issue at least.

**Comment by jacob-pro** [comment]
Yep, feel free to close this :)
The implemented fix solved the original issue my user was observing.

**Comment by stephaneyfx** [comment]
Great! Thank you very much for your continued work on this crate.
