### ISSUE TITLE
Question: is returning a stream of monitors a good idea?

### ISSUE THREAD

**Issue by jacob-pro** [stephaneyfx/brightness#8]
Hi @stephaneyfx 

I am wondering if the current API, or at least the usage in the windows portion of the crate is a good idea.

Because of the streams API it means that it encourages users to add computations in between fetching each monitor, e.g. by inserting a print statement in the `brightness_devices()` function and then running the example on windows:

```
Getting monitor \\.\DISPLAY1\Monitor0
Brightness of device \\.\DISPLAY1\Monitor0 is 65%
Brightness of device \\.\DISPLAY1\Monitor0 is 65%
Getting monitor \\.\DISPLAY2\Monitor0
Brightness of device \\.\DISPLAY2\Monitor0 is 65%
Brightness of device \\.\DISPLAY2\Monitor0 is 65%
```

And if these computations in between take time it increases the risk of errors caused by attaching/detaching monitors -  e.g. the `SysError::EnumerationMismatch` or `SysError::DeviceInfoMissing`.

In my opinion it would be best if the monitors were all detected and returned together, such that the ordering would look like: 

```
Getting monitor \\.\DISPLAY1\Monitor0
Getting monitor \\.\DISPLAY2\Monitor0
Brightness of device \\.\DISPLAY1\Monitor0 is 65%
Brightness of device \\.\DISPLAY1\Monitor0 is 65%
Brightness of device \\.\DISPLAY2\Monitor0 is 65%
Brightness of device \\.\DISPLAY2\Monitor0 is 65%
```

In theory the same issue could happen on Linux? i.e. The backlight directory is read, device 1 is returned then a user application does some computation (maybe updating a UI etc.), meanwhile device 2 is disconnected, when the stream reaches device 2 it returns an error because the path no longer exists.

I am wondering if it would be better and make a lot more sense if the signature was something like:

```async fn brightness_devices() -> Vec<Result<Brightness, SysError>>```

i.e. brightness_devices() should really be a complete snapshot of all the monitors at a point in time

Or if you don't want to change the whole API, can we at least change windows to collect() its results first before returning them?

**Comment by stephaneyfx** [comment]
Hi @jacob-pro,

I agree that it makes sense to collect all devices on Windows instead of generating them lazily. As you pointed out,

**Comment by stephaneyfx** [comment]
_Sorry for mistakenly closing the issue. The button is too close to the comment field._

Hi @jacob-pro ,

I agree that this is an issue in the Windows implementation. As you pointed out, the device info map and list of monitors are cached before the iteration begins, and so given that we do not have control over the iteration and how long it lasts, it is more likely for a device to be connected or disconnected, causing the initial cache to become outdated.

As far as I can tell, the linux implementation is not affected. It walks through the contents of a directory lazily and there is nothing cached before the iteration starts (i.e. even the contents of the directory are not cached, unless `read_dir` does it). Of course a `Brightness` value yielded by the iterator could become stale if the corresponding device is disconnected.

Does that make sense?

I think the issue in the Windows implementation can be alleviated by doing:
```rust
futures::stream::iter(hmonitors.into_iter().flat_map(...).collect::<Vec<_>>())
```

Please let me know if you want to take care of it or if I should do it.

Thank you for reporting the issue.
